---
- name: Install packages
  dnf:
    name:
      - git
      - unzip
      - wget
      - curl
      - tar
      - python3-pip
    state: present

- name: Install AWS CLI
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
    unzip -o /tmp/awscliv2.zip -d /tmp
    /tmp/aws/install --update
  args:
    creates: /usr/local/bin/aws

- name: Install Helm
  shell: |
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm