---
- name: Install Java 21
  dnf:
    name:
      - java-21-openjdk
      - java-21-openjdk-devel
    state: present

- name: Add Jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

- name: Install Jenkins
  dnf:
    name: jenkins
    state: present

- name: Enable Jenkins
  systemd:
    name: jenkins
    enabled: yes
    state: started