[k8s_master]
10.0.1.10

[k8s_workers]
10.0.1.11
10.0.2.11

[devops]
10.0.1.20

[mysql]
10.0.10.10

[cassandra]
10.0.20.10

[all_nodes:children]
k8s_master
k8s_workers
devops
mysql
cassandra
