[k8s_master]
40.192.1.30

[k8s_workers]
16.112.122.70
98.130.84.159

[devops]
16.112.60.165

[mysql]
mysql-server ansible_host=mysql

[cassandra]
cassandra-server ansible_host=cassandra

[all_nodes:children]
k8s_master
k8s_workers
devops
mysql
cassandra

[all:vars]
ansible_user=ec2-user
ansible_python_interpreter=/usr/bin/python3