---
- name: Kibana

  hosts: k8s_master

  become: yes

  tasks:

    - name: Add Elastic Repo
      shell: |
        helm repo add elastic \
        https://helm.elastic.co

    - name: Update Helm Repositories
      shell: helm repo update

    - name: Install Kibana
      shell: |
        helm upgrade --install kibana \
        elastic/kibana \
        --namespace logging \
        --create-namespace

      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf