---
- name: Deploy Monitoring Stack

  hosts: k8s_master

  become: yes

  tasks:

    - name: Add monitoring repo
      shell: |
        /usr/local/bin/helm repo add prometheus-community \
        https://prometheus-community.github.io/helm-charts
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Update repo
      shell: |
        /usr/local/bin/helm repo update
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Install kube-prometheus-stack
      shell: |
        helm upgrade --install monitoring \
        prometheus-community/kube-prometheus-stack \
        --namespace monitoring \
        --create-namespace \
        --wait \
        --timeout 15m
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
        PATH: "/usr/local/bin:{{ ansible_env.PATH }}"