---
- name: Deploy NGINX Ingress

  hosts: k8s_master

  become: yes

  tasks:

    - name: Add ingress repo
      shell: |
        helm repo add ingress-nginx \
        https://kubernetes.github.io/ingress-nginx

    - name: Update repos
      shell: helm repo update

    - name: Install ingress
      shell: |
        helm upgrade --install ingress-nginx \
        ingress-nginx/ingress-nginx \
        --namespace ingress-nginx \
        --create-namespace

      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf