apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: frontend-monitor

spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: http
    interval: 15s
    path: /